module.exports = {
  color: {
    fondo: '#fff',
    fondoSutil: '#f8f9fa',
    fondoTab: '#f1f3f5',
    borde: '#eee',
    bordeFuerte: '#ced4da',
    bordeInput: '#ccc',
    textoPrimario: '#1a1a1a',
    textoSecundario: '#495057',
    textoTerciario: '#666',
    textoDeshabilitado: '#999',
    textoInactivo: '#888',
    overlay: 'rgba(0, 0, 0, 0.5)',
    sombra: '#000',
    primario: '#1c7ed6',
    primarioOscuro: '#1971c2',
    primarioSuave: '#e7f5ff',
    exito: '#2b8a3e',
    peligro: '#e03131',
    peligroSuave: '#fff0f0',
    advertencia: '#e8590c',
    advertenciaSuave: '#fff4e6',
    oscuro: '#333',
  },
  espacio: { xs: 4, sm: 8, md: 12, base: 16, lg: 20, xl: 24, xxl: 32 },
  radio: { sm: 8, md: 12, lg: 16, xl: 20, completo: 999 },
  toqueMinimo: 44,
  sombraTarjeta: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 6, elevation: 2 },
  sombraFlotante: { shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.12, shadowRadius: 16, elevation: 8 },
  sombraSuave: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 3, elevation: 1 },
};
